// Copyright (c) Andrew Arnott. All rights reserved.
// Licensed under the MS-PL license. See LICENSE.txt file in the project root for full license information.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;

namespace CodeGeneration.Roslyn
{
    /// <summary>
    /// Contains <see cref="CompilationUnitSyntax"/> additions generated by the <see cref="IRichCodeGenerator"/>.
    /// </summary>
    public class RichGenerationResult
    {
        /// <summary>
        /// Gets or sets the <see cref="MemberDeclarationSyntax"/> to add to generated <see cref="CompilationUnitSyntax"/>.
        /// </summary>
        public List<ChangeMember> Members { get; set; } = new List<ChangeMember>();

        /// <summary>
        /// Gets or sets the <see cref="UsingDirectiveSyntax"/> to add to generated <see cref="CompilationUnitSyntax"/>.
        /// </summary>
        public SyntaxList<UsingDirectiveSyntax> Usings { get; set; } = default;

        /// <summary>
        /// Gets or sets the <see cref="ExternAliasDirectiveSyntax"/> to add to generated <see cref="CompilationUnitSyntax"/>.
        /// </summary>
        public SyntaxList<ExternAliasDirectiveSyntax> Externs { get; set; } = default;

        /// <summary>
        /// Gets or sets the <see cref="AttributeListSyntax"/> to add to generated <see cref="CompilationUnitSyntax"/>.
        /// </summary>
        public SyntaxList<AttributeListSyntax> AttributeLists { get; set; } = default;
    }

    public class ChangeMember
    {
        public SyntaxNode OldMember { get; private set; }

        public SyntaxNode BaseMember { get; private set; }

        public SyntaxNode NewMember { get; private set; }

        private ChangeMember(SyntaxNode oldMember, SyntaxNode baseMember, SyntaxNode newMember)
        {
            OldMember = oldMember;
            BaseMember = baseMember;
            NewMember = newMember;
        }

        public static ChangeMember AddMember(SyntaxNode baseMember, SyntaxNode newMember)
        {
            return new ChangeMember(null, baseMember, newMember);
        }

        public static ChangeMember ReplaceMember(SyntaxNode oldMember, SyntaxNode newMember)
        {
            return new ChangeMember(oldMember, null, newMember);
        }

        public static ChangeMember RemoveMember(SyntaxNode oldMember)
        {
            return new ChangeMember(oldMember, null, null);
        }
    }
}
